//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_Demo.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogFile
    {
        public int ID { get; set; }
        public int FK_Employee_ID { get; set; }
        public string Opreation_name { get; set; }
        public System.DateTime LogDate { get; set; }
        public string Notes { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
