//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_Demo.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rays
    {
        public int Ray_ID { get; set; }
        public string Ray_Name { get; set; }
        public string Ray_Code { get; set; }
        public double Price { get; set; }
        public string Notes { get; set; }
    }
}
