using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using LIMS_Demo.DB;
using DevExpress.XtraGrid;
using DevExpress.XtraVerticalGrid.Rows;

namespace LIMS_Demo.View
{
    public partial class EnquiryFrm : Form
    {
        LIMS db = new LIMS();
        List<Enquirys> enquirys = new List<Enquirys>();
        DataTable table = new DataTable();
        public EnquiryFrm()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            LIMS_Demo.DB.LIMS dbContext = new LIMS_Demo.DB.LIMS();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Enquirys.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    dvgEnquirys.DataSource = dbContext.Enquirys.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void EnquiryFrm_Load(object sender, EventArgs e)
        {
            
        }


    }
}
