using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using DevExpress.Utils;

namespace LIMS_Demo.View
{
    public partial class Login_LogoutFrm : Form
    {
        protected override CreateParams CreateParams
        {
            get
            {
                const int CS_DROPSHADOW = 0x20000;
                CreateParams cp = base.CreateParams;
                cp.ClassStyle |= CS_DROPSHADOW;
                return cp;
            }
        }
        public Login_LogoutFrm()
        {
            
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            LIMS_Demo.DB.LIMS dbContext = new LIMS_Demo.DB.LIMS();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Login_Logout.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    dvgTrakingSystem.DataSource = dbContext.Login_Logout.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void rjButton9_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void Login_LogoutFrm_Paint(object sender, PaintEventArgs e)
        {
            ControlPaint.DrawBorder(e.Graphics, ClientRectangle, Color.FromArgb(200, 168, 168, 168), ButtonBorderStyle.Solid);

        }

        private void dvgTrakingSystem_Load(object sender, EventArgs e)
        {
            colLogin.DisplayFormat.FormatType = FormatType.DateTime;
            colLogin.DisplayFormat.FormatString = "dd/MM/yyyy hh:mm:ss tt";

            collogout.DisplayFormat.FormatType = FormatType.DateTime;
            collogout.DisplayFormat.FormatString = "dd/MM/yyyy hh:mm:ss tt";
        }
    }
}
